name: GPGN486

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - jupyterlab
  - pandas
  - geopandas
  - matplotlib
  - shapely
  - obspy
  - cartopy
  - numpy
  pip:
    - swprocess